import type { Metadata } from "next";
 import Navbar from "../Components/ui/Navbar/Navber";
import Footer from "../Components/ui/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <html lang="en">
  <Navbar />
    {children}
    <Footer />
    </html>;
}
